name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump"
        required: true
        type: choice
        options:
          - none
          - patch
          - minor
          - major
        default: "none"
      custom_version:
        description: "Custom version (Optional)"
        required: false
        type: string

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          brew install swiftlint swiftformat
          gem install fastlane

      - name: Import certificates
        env:
          CERTIFICATES_P12: ${{ secrets.CERTIFICATES_P12 }}
          CERTIFICATES_PASSWORD: ${{ secrets.CERTIFICATES_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          echo -n "$CERTIFICATES_P12" | base64 --decode -o $CERTIFICATE_PATH
          security import $CERTIFICATE_PATH -P "$CERTIFICATES_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Bump version
        id: version
        run: |
          chmod +x scripts/bump_version.sh
          if [ -n "${{ github.event.inputs.custom_version }}" ]; then
            ./scripts/bump_version.sh "${{ github.event.inputs.custom_version }}"
          else
            ./scripts/bump_version.sh "${{ github.event.inputs.version }}"
          fi

      - name: Run tests
        run: fastlane test
        continue-on-error: true

      - name: Build and upload to TestFlight
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: fastlane beta

      - name: Cleanup keychain
        if: always()
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db || true

      - name: Create release
        if: github.event.inputs.version != 'none'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_NUMBER }}
          name: v${{ env.VERSION_NUMBER }}
          body: |
            Build ${{ env.BUILD_NUMBER }} uploaded to TestFlight.

            ${{ github.event.head_commit.message }}
          draft: true
          generate_release_notes: true
